export default {
  name: 'Adele Tafazzoli',
  home: 'HOME',
  about: 'ABOUT',
  portfolios: 'PORTFOLIOS',
  contact: 'CONTACT',
  resume: 'RESUME',
  hi1: 'Hi, I am ',
  hi2: '',
  desc1:
    'I am an amateur frontend web developer. I love learning more about providing clean code and pixel perfect design.',
  aboutme: 'About Me',
  fullname: 'Full Name',
  age: 'Age',
  nationality: 'Nationality',
  languages: 'Languages',
  ag: '34',
  EP: 'English,Persian',
  iranian: 'Iranian',
  downloadcv: 'Download CV',
  services: 'SERVICES',
  webdesign: 'Web Design',
  webdevelopment: 'Web Development',
  mobileapplication: 'Mobile Application',
  desc:
    'I have some knowledge of this area and I am eager to learn about it more and more',
  myskills: 'My Skills',
  businessexperience: 'Business Experience',
  educationalqualification: 'Educational Qualifications',
  work: [
    {
      id: -1,
      date: '',
      title: '',
      subtitle: '',
      content: '',
    },
    {
      id: 0,
      date: '2011-2013',
      title: 'chemical engineer',
      subtitle: 'Faraz Compressor Company',
      content: 'I had worked as manager of R&D section',
    },
    {
      id: 1,
      date: '2008-2018',
      title: 'Mathematic teacher ',
      subtitle: 'entrance exam of Iranian universities',
      content: 'I have been working as a mathematic tutor for over 10 years',
    },
    {
      id: 2,
      date: '2017-2019',
      title: 'manager of a daycare ',
      subtitle: 'Nava play house',
      content:
        'I started this business but for some difficulties I closed it two years after that',
    },
    {
      id: -2,
      date: '',
      title: '',
      subtitle: '',
      content: '',
    },
  ],
  education: [
    {
      id: -1,
      date: '',
      title: '',
      subtitle: '',
      content: '',
    },
    {
      id: 0,
      date: '2003-2007',
      title: 'Master of Sience',
      subtitle: 'Tehran University',
      content:
        'I start my educational journey in chemical engineering at university of Tehran',
    },
    {
      id: 1,
      date: '2008-2010',
      title: 'Bachelor of sience ',
      subtitle: 'Tehran University',
      content:
        'I start my educational journey in chemical engineering at university of Tehran',
    },
    {
      id: -2,
      date: '',
      title: '',
      subtitle: '',
      content: '',
    },
  ],
  contactme: 'CONTACT ME',
  getintouch: 'Get In Touch',
  entername: 'Enter yor name',
  enteremail: 'Enter yor email',
  entersubject: 'Enter yor subject',
  entermessage: 'Enter yor message',
  sendmessage: 'SEND MESSAGE',
  phonenumber: '+989122550896',
  emailaddress: 'adeleh.tafazzoli@gmail.com',
  addresss: 'Nahid street,Marzdaran Blvd,Tehran,Iran',
  phone: 'Phone',
  email: 'Email',
  address: 'Address',
};
